Problem Statement : Hospital Patient Data Analysis
Context:
A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.
Tasks:
1.	Load the patient dataset and show summary with info().
2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].
3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].
4.	Use groupby to find total bill amount per department.
5.	Remove duplicate patient records based on PatientID.
6.	Fill missing BillAmount values with the mean bill amount.
7.	Merge the billing dataset with patient dataset on PatientID.
8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).
9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).
Expected Outcome:
•	Final cleaned dataset with accurate billing info.
•	All missing values handled, merged dataset across PatientID.
•	Ability to perform further analytics on department-wise revenue or doctor performance.

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df1=pd.read_csv("Billing_data.csv")

In [3]:
df2=pd.read_csv("Patient_data.csv")

In [4]:
df1

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [5]:
df2

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [8]:
df1.describe()

        PatientID  InsuranceCovered  FinalAmount
count    5.000000          5.000000     5.000000
mean   103.000000       2000.000000  3740.000000
std      1.581139        790.569415   798.749022
min    101.000000       1000.000000  3000.000000
25%    102.000000       1500.000000  3200.000000
50%    103.000000       2000.000000  3500.000000
75%    104.000000       2500.000000  4000.000000
max    105.000000       3000.000000  5000.000000

In [9]:
df2.describe()

        PatientID   BillAmount  ReceptionistID
count    6.000000     4.000000        6.000000
mean   102.666667  5925.000000        1.666667
std      1.632993  1192.686044        0.816497
min    101.000000  5000.000000        1.000000
25%    101.250000  5000.000000        1.000000
50%    102.500000  5600.000000        1.500000
75%    103.750000  6525.000000        2.000000
max    105.000000  7500.000000        3.000000

In [10]:
df1.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [11]:
df2.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [12]:
df2.duplicated().isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [13]:
df2

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [14]:
num = df2.select_dtypes(['int','float'])
num

   PatientID  BillAmount  ReceptionistID
0        101      5000.0               1
1        102         NaN               2
2        103      7500.0               1
3        104      6200.0               3
4        105         NaN               2
5        101      5000.0               1

In [15]:
cate = df2.select_dtypes(["object"])
cate

      Name   Department     Doctor       CheckInTime
0    Alice   Cardiology  Dr. Smith  2023-01-10 09:00
1      Bob    Neurology   Dr. John  2023-01-11 10:30
2  Charlie  Orthopedics    Dr. Lee  2023-01-12 11:00
3    David   Cardiology  Dr. Smith  2023-01-13 12:00
4      Eva  Dermatology   Dr. Rose  2023-01-14 08:45
5    Alice   Cardiology  Dr. Smith  2023-01-10 09:00

In [16]:
num.mean()

PatientID          102.666667
BillAmount        5925.000000
ReceptionistID       1.666667
dtype: float64

In [17]:
df2[["PatientID","Department","Doctor","BillAmount"]]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [18]:
df2.drop('ReceptionistID', axis = 1 , inplace=True)

In [19]:
df2.drop('CheckInTime' , axis =1 , inplace=True )

In [20]:
df2

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [21]:
df2['BillAmount'].fillna(df2['BillAmount'].mean() , inplace=True)

In [22]:
df2

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      5925.0
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      5925.0
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [23]:
df2.drop_duplicates(inplace=True)

In [24]:
df2

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      5925.0
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      5925.0

In [25]:
billing_total=df2.groupby('Department')['BillAmount'].sum().reset_index()
billing_total

    Department  BillAmount
0   Cardiology     11200.0
1  Dermatology      5925.0
2    Neurology      5925.0
3  Orthopedics      7500.0

In [26]:
merging=pd.merge(df1,df2, on='PatientID')

In [27]:
merging

,PatientID,InsuranceCovered,FinalAmount,Name,Department,Doctor,BillAmount
0,101,2000,3000,Alice,Cardiology,Dr. Smith,5000.0
1,102,1500,3500,Bob,Neurology,Dr. John,5925.0
2,103,2500,5000,Charlie,Orthopedics,Dr. Lee,7500.0
3,104,3000,3200,David,Cardiology,Dr. Smith,6200.0
4,105,1000,4000,Eva,Dermatology,Dr. Rose,5925.0

In [28]:
new_patients = pd.DataFrame({
    'PatientID': [106, 107],
    'Name': ['John', 'Tony'],
    'Department': ['Cardiology', 'Orthopaedics'],
    'Doctor': ['Dr. Lee', 'Dr. Rose'],
    'BillAmount': [4500.000000, 6200.000000]
})

patient_updated = pd.concat([df2, new_patients], ignore_index=True)
patient_updated

   PatientID     Name    Department     Doctor  BillAmount
0        101    Alice    Cardiology  Dr. Smith      5000.0
1        102      Bob     Neurology   Dr. John      5925.0
2        103  Charlie   Orthopedics    Dr. Lee      7500.0
3        104    David    Cardiology  Dr. Smith      6200.0
4        105      Eva   Dermatology   Dr. Rose      5925.0
5        106     John    Cardiology    Dr. Lee      4500.0
6        107     Tony  Orthopaedics   Dr. Rose      6200.0

In [30]:
final_dataset = pd.merge(patient_updated, df1,on='PatientID',how='left')

In [31]:
final_dataset['InsuranceCovered'].fillna(0, inplace=True)

In [32]:
final_dataset['FinalAmount'].fillna(final_dataset['BillAmount'], inplace=True)

In [33]:
final_dataset

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,5925.0,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.0,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,5925.0,1000.0,4000.0
5,106,John,Cardiology,Dr. Lee,4500.0,0.0,4500.0
6,107,Tony,Orthopaedics,Dr. Rose,6200.0,0.0,6200.0